import type { InspectionSection } from '@/types'

export const SECTIONS: InspectionSection[] = [
  {
    key: 'driveway',
    title: 'Driveway - Walks - Grounds',
    items: [
      { id: 'driveway_surface', label: 'Driveway Surface' },
      { id: 'walkways', label: 'Walkways / Sidewalks' },
      { id: 'steps_stoops', label: 'Steps / Stoops' },
      { id: 'retaining_walls', label: 'Retaining Walls' },
      { id: 'fencing_gates', label: 'Fencing / Gates' },
      { id: 'landscaping_grading', label: 'Landscaping / Grading' },
      { id: 'site_drainage', label: 'Site Drainage' },
      { id: 'vegetation_clearance', label: 'Vegetation Clearance from Structure' },
    ],
  },
  {
    key: 'roof',
    title: 'Roof System',
    items: [
      { id: 'roof_covering', label: 'Roof Covering / Shingles' },
      { id: 'gutters_downspouts', label: 'Gutters & Downspouts' },
      { id: 'flashing', label: 'Flashing (Valleys, Ridges, Edges)' },
      { id: 'skylights', label: 'Skylights' },
      { id: 'chimney_exterior', label: 'Chimney (Exterior)' },
      { id: 'roof_vents', label: 'Roof Vents' },
      { id: 'fascia_soffits', label: 'Fascia & Soffits' },
      { id: 'roof_decking', label: 'Roof Decking (Visible)' },
    ],
  },
  {
    key: 'exterior',
    title: 'Exterior System',
    items: [
      { id: 'wall_cladding', label: 'Wall Cladding / Siding' },
      { id: 'exterior_trim', label: 'Exterior Trim' },
      { id: 'exterior_windows', label: 'Windows (Exterior)' },
      { id: 'exterior_doors', label: 'Entry Doors' },
      { id: 'garage_door', label: 'Garage Door(s)' },
      { id: 'garage_door_opener', label: 'Garage Door Opener' },
      { id: 'caulking_sealants', label: 'Caulking & Sealants' },
      { id: 'exterior_lighting', label: 'Exterior Lighting' },
      { id: 'exterior_outlets', label: 'Exterior Electrical Outlets (GFCI)' },
      { id: 'hose_bibs', label: 'Hose Bibs' },
    ],
  },
  {
    key: 'kitchen',
    title: 'Kitchen - Appliances',
    items: [
      { id: 'refrigerator', label: 'Refrigerator' },
      { id: 'range_oven', label: 'Range / Oven / Cooktop' },
      { id: 'dishwasher', label: 'Dishwasher' },
      { id: 'garbage_disposal', label: 'Garbage Disposal' },
      { id: 'microwave', label: 'Microwave' },
      { id: 'kitchen_sink_faucet', label: 'Kitchen Sink & Faucet' },
      { id: 'countertops', label: 'Countertops' },
      { id: 'cabinets', label: 'Cabinets' },
      { id: 'range_hood', label: 'Range Hood / Ventilation' },
    ],
  },
  {
    key: 'bathrooms',
    title: 'Bathrooms',
    items: [
      { id: 'toilets', label: 'Toilet(s)' },
      { id: 'sinks_faucets', label: 'Sink(s) & Faucet(s)' },
      { id: 'bathtub_shower', label: 'Bathtub / Shower' },
      { id: 'exhaust_fan', label: 'Exhaust Fan(s)' },
      { id: 'bathroom_flooring', label: 'Flooring' },
      { id: 'bathroom_walls_ceiling', label: 'Walls & Ceiling' },
      { id: 'caulking_grout', label: 'Caulking & Grout' },
      { id: 'water_pressure', label: 'Water Pressure' },
    ],
  },
  {
    key: 'structure',
    title: 'Structure System',
    items: [
      { id: 'foundation', label: 'Foundation (Visible)' },
      { id: 'basement_crawl', label: 'Basement / Crawl Space' },
      { id: 'columns_posts', label: 'Structural Columns / Posts / Beams' },
      { id: 'floor_structure', label: 'Floor Structure / Joists' },
      { id: 'wall_structure', label: 'Wall Structure (Visible)' },
      { id: 'roof_structure', label: 'Roof Structure (Attic View)' },
    ],
  },
  {
    key: 'insulation',
    title: 'Insulation & Ventilation',
    items: [
      { id: 'attic_insulation', label: 'Attic Insulation' },
      { id: 'wall_insulation', label: 'Wall Insulation (Visible)' },
      { id: 'basement_insulation', label: 'Basement / Crawl Space Insulation' },
      { id: 'attic_ventilation', label: 'Attic Ventilation' },
      { id: 'vapor_barrier', label: 'Vapor Barrier' },
    ],
  },
  {
    key: 'electrical',
    title: 'Electrical System',
    items: [
      { id: 'service_panel', label: 'Service Panel / Breaker Box' },
      { id: 'main_disconnect', label: 'Main Disconnect' },
      { id: 'branch_circuits', label: 'Branch Circuit Wiring' },
      { id: 'outlets_switches', label: 'Outlets & Switches' },
      { id: 'gfci_protection', label: 'GFCI Protection (Kitchens, Baths, Exterior)' },
      { id: 'afci_protection', label: 'Arc Fault Protection (AFCI)' },
      { id: 'smoke_detectors', label: 'Smoke Detectors' },
      { id: 'co_detectors', label: 'Carbon Monoxide Detectors' },
      { id: 'grounding', label: 'Grounding & Bonding' },
    ],
  },
  {
    key: 'plumbing',
    title: 'Plumbing System',
    items: [
      { id: 'water_supply_source', label: 'Water Supply Source' },
      { id: 'main_shutoff', label: 'Main Water Shutoff' },
      { id: 'supply_piping', label: 'Supply Piping' },
      { id: 'drain_waste_vent', label: 'Drain / Waste / Vent Piping' },
      { id: 'water_heater', label: 'Water Heater' },
      { id: 'water_heater_connections', label: 'Water Heater Connections & Relief Valve' },
      { id: 'sump_pump', label: 'Sump Pump' },
      { id: 'sewage_ejector', label: 'Sewage Ejector Pump' },
    ],
  },
  {
    key: 'heating',
    title: 'Heating System',
    items: [
      { id: 'furnace_boiler', label: 'Furnace / Boiler Unit' },
      { id: 'heat_exchanger', label: 'Heat Exchanger (Visible)' },
      { id: 'distribution_system', label: 'Distribution System (Ducts / Radiators)' },
      { id: 'flue_chimney', label: 'Flue / Chimney Connection' },
      { id: 'heating_filters', label: 'Air Filters' },
      { id: 'thermostat_heat', label: 'Thermostat' },
    ],
  },
  {
    key: 'ac',
    title: 'Central Air Conditioning System',
    items: [
      { id: 'condenser_unit', label: 'Condenser / Compressor Unit (Exterior)' },
      { id: 'air_handler', label: 'Air Handler / Evaporator (Interior)' },
      { id: 'refrigerant_lines', label: 'Refrigerant Lines' },
      { id: 'condensate_drain', label: 'Condensate Drain' },
      { id: 'ac_filters', label: 'Air Filters' },
      { id: 'thermostat_ac', label: 'Thermostat' },
    ],
  },
  {
    key: 'interior',
    title: 'Interior Surfaces - Windows - Doors',
    items: [
      { id: 'ceilings', label: 'Ceilings' },
      { id: 'walls', label: 'Walls' },
      { id: 'floors', label: 'Floors' },
      { id: 'interior_windows', label: 'Interior Windows' },
      { id: 'interior_doors', label: 'Interior Doors' },
      { id: 'stairs_railings', label: 'Stairs / Handrails / Railings' },
      { id: 'closets', label: 'Closets' },
    ],
  },
  {
    key: 'fireplace',
    title: 'Fireplace',
    items: [
      { id: 'firebox', label: 'Firebox / Firebrick' },
      { id: 'damper', label: 'Damper' },
      { id: 'flue_interior', label: 'Flue / Chimney (Interior)' },
      { id: 'hearth', label: 'Hearth & Surround' },
      { id: 'mantel', label: 'Mantel' },
      { id: 'gas_log', label: 'Gas Log Assembly' },
    ],
  },
  {
    key: 'laundry',
    title: 'Laundry',
    items: [
      { id: 'washer_connection', label: 'Washer Connection' },
      { id: 'dryer_connection', label: 'Dryer Connection' },
      { id: 'dryer_vent', label: 'Dryer Vent' },
      { id: 'laundry_sink', label: 'Laundry Sink' },
      { id: 'laundry_area', label: 'Laundry Area (Flooring & Surroundings)' },
    ],
  },
  {
    key: 'other',
    title: 'Other Info',
    items: [
      { id: 'garage_interior', label: 'Garage (Interior)' },
      { id: 'garage_floor', label: 'Garage Floor' },
      { id: 'garage_fire_door', label: 'Garage Fire Door' },
      { id: 'pool_spa', label: 'Pool / Spa (if present)' },
      { id: 'additional_structures', label: 'Shed / Additional Structures' },
    ],
  },
]

export const STATUS_CONFIG = {
  ok: {
    label: 'OK',
    color: '#16a34a',
    bg: 'bg-green-100',
    text: 'text-green-800',
    border: 'border-green-400',
    activeBg: 'bg-green-500',
    activeText: 'text-white',
    dot: '✓',
  },
  repair: {
    label: 'Needs Repair',
    color: '#d97706',
    bg: 'bg-yellow-100',
    text: 'text-yellow-800',
    border: 'border-yellow-400',
    activeBg: 'bg-yellow-500',
    activeText: 'text-white',
    dot: '⚠',
  },
  replace: {
    label: 'Needs Replacement',
    color: '#dc2626',
    bg: 'bg-red-100',
    text: 'text-red-800',
    border: 'border-red-400',
    activeBg: 'bg-red-500',
    activeText: 'text-white',
    dot: '✗',
  },
  na: {
    label: 'N/A',
    color: '#9ca3af',
    bg: 'bg-gray-100',
    text: 'text-gray-500',
    border: 'border-gray-300',
    activeBg: 'bg-gray-400',
    activeText: 'text-white',
    dot: '—',
  },
} as const
